### ISSUE TITLE
Add About us 

### ISSUE THREAD

**Issue by deepraj02** [OnCampus-Community/Website_OnCampus#17]
![image](https://user-images.githubusercontent.com/63138398/218275501-b3f56e88-134f-42d9-9003-929ff9133efb.png)

Content will be shared

**Comment by itsdchanda** [comment]
Here's the content for the About Us section:

Who We Are:

On-Campus is the ultimate developer community, providing a platform where developers worldwide can connect, collaborate, and learn from each other. We offer a supportive and inclusive environment where developers can get their questions answered, seek advice, find interesting projects, and connect with like-minded developers.

What We Do:

We organize webinars, community events, and contests, bringing together a unique community of global students and mentors. Our website offers a wide range of articles, tutorials, and news updates to keep you up-to-date with the latest technology trends.

Our Mission:

At On-Campus, we are dedicated to empowering developers and providing them with the resources to succeed. Our mission is to create a platform where developers can connect, collaborate, and create innovative solutions that have the power to change the world.

What Sets Us Apart:

We understand that developers thrive in a supportive and inclusive environment. At On-Campus, we strive to build a strong community of developers that fosters support, collaboration, and growth. Our community is unique in its inclusivity, welcoming developers from all backgrounds and experience levels.

Our Offerings:

Community Events:

Our community events provide a platform for developers to connect, collaborate, and learn from each other. We organize events that cater to all experience levels, offering a supportive and inclusive environment that encourages growth and learning.

Webinars:

Our webinars cover a wide range of topics, from software development to project management. Our webinars are presented by industry experts and are designed to provide our community with the knowledge and resources they need to succeed.

Contests:

We organize contests that challenge our community to create innovative solutions to real-world problems. Our contests are designed to foster creativity, innovation, and collaboration.

Internships and Jobs:

We help our community find internships and jobs, connecting them with potential employers worldwide.

Our Team:

Our team is made up of experienced professionals with a passion for technology. We are dedicated to creating a platform that empowers developers and provides them with the resources they need to succeed. We believe that technology has the power to change the world, and we are committed to creating a community that enables developers to create innovative solutions that make a difference.
