### ISSUE TITLE
About us 

### ISSUE THREAD

**Issue by deepraj02** [OnCampus-Community/Website_OnCampus#21]
![image](https://user-images.githubusercontent.com/63138398/218301353-2a715872-451b-4e1f-b81b-f506b6235ea5.png)

Replace the text with the following:

# Unleash Your Potential: Join the OnCampus Community Today 🚀💻 

### Take Your Developer Journey to the Next Level with OnCampus 🚀 Connect, Collaborate, and Achieve Greatness 💻

Change the Existting Buttons with 

1. Join Community

**Comment by akscoder082003** [comment]
![Screenshot_20230212_172218](https://user-images.githubusercontent.com/109755100/218309405-d53f2401-46d5-4864-9529-6df2229f9231.png)


Did you mean this full text?

**Comment by akscoder082003** [comment]
![Screenshot_20230212_174802](https://user-images.githubusercontent.com/109755100/218310581-68d21cdf-bcde-4186-9427-7ac276901244.png)

**Comment by itsdchanda** [comment]
Yes

**Comment by akscoder082003** [comment]
now what I have to do next,

**Comment by deepraj02** [comment]
First raise a PR, will merge that

**Comment by deepraj02** [comment]
![image](https://user-images.githubusercontent.com/63138398/218312250-19c65cc9-6cad-45a3-80be-fe94ab7325a4.png)

you can Now remove the selected texts

**Comment by deepraj02** [comment]
@akscoder082003
